name: NYC Dev & Permits → CSV daily

on:
  schedule:
    - cron: '0 13 * * *'   # 每天 09:00 ET（夏令时）；GitHub 使用 UTC
  workflow_dispatch: {}     # 支持手动 Run workflow

permissions:
  contents: write           # 允许提交 CSV 到仓库

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper and save CSV
        env:
          NYC_SODA_APP_TOKEN: ${{ secrets.NYC_SODA_APP_TOKEN }}   # 可选，提高 Open Data 稳定性
        run: |
          python scraper.py nyc_developers_daily.csv
          mkdir -p public
          cp nyc_developers_daily.csv public/nyc_developers_daily.csv

      - name: Commit CSV to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update daily CSV $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit."
          git push
