name: NYC Dev & Permits Daily → Google Sheet (append)

on:
  schedule:
    - cron: '0 13 * * *'   # 每天 09:00 ET（夏令时）；cron 使用 UTC
  workflow_dispatch: {}     # 支持手动触发

permissions:
  contents: read

concurrency:
  group: nyc-dev-permits
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser python-dateutil pandas gspread google-auth
      - name: Run scraper → Google Sheet (append)
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          NYC_SODA_APP_TOKEN: ${{ secrets.NYC_SODA_APP_TOKEN }}
          GSHEET_TAB: Daily
          LOOKBACK_HOURS: 24
        run: python scraper_gsheet.py
