name: NYC Dev & Permits → Google Sheet (OIDC append)

on:
  schedule:
    - cron: '0 13 * * *'   # 每天 09:00 ET（夏令时）；GitHub 用的是 UTC
  workflow_dispatch: {}     # 支持手动“Run workflow”

permissions:
  contents: read
  id-token: write           # 允许 OIDC 登录 GCP

concurrency:
  group: nyc-dev-permits
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # —— 1) 使用 OIDC 无密钥登录 Google —— 
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          # 替换为你的 Workload Identity Provider 资源名（必须改）
          # 形如：projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/GITHUB_POOL/providers/GITHUB_PROVIDER
          workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/GITHUB_POOL/providers/GITHUB_PROVIDER'
          # 替换为你的服务账号邮箱（必须改）
          service_account: 'gsheet-writer@PROJECT_ID.iam.gserviceaccount.com'
          export_environment_variables: true

      # —— 2) Python 环境与依赖 —— 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser python-dateutil pandas \
                      gspread google-auth google-auth-httplib2 google-auth-oauthlib

      # —— 3) 运行脚本：将新数据“追加”到 Google Sheet —— 
      - name: Run scraper → Google Sheet (append)
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}         # 你的 Google Sheet ID（放在仓库 Secrets）
          GSHEET_TAB: Daily                           # 工作表名；如需更换，改这里和/或脚本默认值
          NYC_SODA_APP_TOKEN: ${{ secrets.NYC_SODA_APP_TOKEN }}  # 可选，Open Data token
          LOOKBACK_HOURS: 24                          # 抓取近 24 小时
        run: python scraper_gsheet_oidc.py            # 仓库根目录放同名脚本

